package API_07_03_2022;
/**
   por Rafael Ferreira Goulart
**/
public final class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
        Limpar();
        jL_Mensagem.setText("");
    }
    
    public void Limpar() {
        jTF_ValorX.setText("");
        jTF_ValorY.setText("");
        jTF_Resultado.setText("");
        jL_Mensagem.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jP_Fundo = new javax.swing.JPanel();
        jP_Fundo2 = new javax.swing.JPanel();
        jP_FundoTitulo = new javax.swing.JPanel();
        jL_Titulo = new javax.swing.JLabel();
        jP_Conteudo = new javax.swing.JPanel();
        jP_FundoVX = new javax.swing.JPanel();
        jTF_ValorX = new javax.swing.JTextField();
        jP_FundoVY = new javax.swing.JPanel();
        jTF_ValorY = new javax.swing.JTextField();
        jL_Igual = new javax.swing.JLabel();
        jP_OpcoesEResultado = new javax.swing.JPanel();
        jTF_Resultado = new javax.swing.JTextField();
        jL_Igual1 = new javax.swing.JLabel();
        jB_Adicao = new javax.swing.JButton();
        jB_Subtracao = new javax.swing.JButton();
        jB_Multiplicacao = new javax.swing.JButton();
        jB_Divisao = new javax.swing.JButton();
        jB_Limpar = new javax.swing.JButton();
        jL_Mensagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jP_Fundo.setBackground(new java.awt.Color(153, 153, 255));

        jP_Fundo2.setBackground(new java.awt.Color(204, 204, 255));

        jP_FundoTitulo.setBackground(new java.awt.Color(153, 153, 255));

        jL_Titulo.setFont(new java.awt.Font("Sitka Display", 1, 24)); // NOI18N
        jL_Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_Titulo.setText("Menu - Operações Matemáticas");

        javax.swing.GroupLayout jP_FundoTituloLayout = new javax.swing.GroupLayout(jP_FundoTitulo);
        jP_FundoTitulo.setLayout(jP_FundoTituloLayout);
        jP_FundoTituloLayout.setHorizontalGroup(
            jP_FundoTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jL_Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jP_FundoTituloLayout.setVerticalGroup(
            jP_FundoTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jL_Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jP_Conteudo.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout jP_FundoVXLayout = new javax.swing.GroupLayout(jP_FundoVX);
        jP_FundoVX.setLayout(jP_FundoVXLayout);
        jP_FundoVXLayout.setHorizontalGroup(
            jP_FundoVXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_FundoVXLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTF_ValorX, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );
        jP_FundoVXLayout.setVerticalGroup(
            jP_FundoVXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_FundoVXLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTF_ValorX)
                .addContainerGap())
        );

        javax.swing.GroupLayout jP_FundoVYLayout = new javax.swing.GroupLayout(jP_FundoVY);
        jP_FundoVY.setLayout(jP_FundoVYLayout);
        jP_FundoVYLayout.setHorizontalGroup(
            jP_FundoVYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_FundoVYLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTF_ValorY, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );
        jP_FundoVYLayout.setVerticalGroup(
            jP_FundoVYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_FundoVYLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTF_ValorY, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        jL_Igual.setFont(new java.awt.Font("Sitka Display", 1, 24)); // NOI18N
        jL_Igual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_Igual.setText("op");

        jL_Igual1.setFont(new java.awt.Font("Sitka Display", 1, 24)); // NOI18N
        jL_Igual1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jL_Igual1.setText("=");

        jB_Adicao.setText("+");
        jB_Adicao.setToolTipText("Fazer operação matemática");
        jB_Adicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_AdicaoActionPerformed(evt);
            }
        });

        jB_Subtracao.setText("-");
        jB_Subtracao.setToolTipText("Fazer operação matemática");
        jB_Subtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_SubtracaoActionPerformed(evt);
            }
        });

        jB_Multiplicacao.setText("x");
        jB_Multiplicacao.setToolTipText("Fazer operação matemática");
        jB_Multiplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_MultiplicacaoActionPerformed(evt);
            }
        });

        jB_Divisao.setText("/");
        jB_Divisao.setToolTipText("Fazer operação matemática");
        jB_Divisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_DivisaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jP_OpcoesEResultadoLayout = new javax.swing.GroupLayout(jP_OpcoesEResultado);
        jP_OpcoesEResultado.setLayout(jP_OpcoesEResultadoLayout);
        jP_OpcoesEResultadoLayout.setHorizontalGroup(
            jP_OpcoesEResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_OpcoesEResultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jB_Adicao, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jB_Subtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jB_Multiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jB_Divisao, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jL_Igual1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTF_Resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jP_OpcoesEResultadoLayout.setVerticalGroup(
            jP_OpcoesEResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_OpcoesEResultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_OpcoesEResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTF_Resultado)
                    .addComponent(jL_Igual1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jB_Adicao, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_Subtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_Multiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_Divisao, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jB_Limpar.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        jB_Limpar.setText("Limpar Espaços");
        jB_Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_LimparActionPerformed(evt);
            }
        });

        jL_Mensagem.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jL_Mensagem.setForeground(new java.awt.Color(255, 0, 0));
        jL_Mensagem.setText("Mensagem");

        javax.swing.GroupLayout jP_ConteudoLayout = new javax.swing.GroupLayout(jP_Conteudo);
        jP_Conteudo.setLayout(jP_ConteudoLayout);
        jP_ConteudoLayout.setHorizontalGroup(
            jP_ConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_ConteudoLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jP_ConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jL_Mensagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jB_Limpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jP_OpcoesEResultado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jP_ConteudoLayout.createSequentialGroup()
                        .addComponent(jP_FundoVX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jL_Igual, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jP_FundoVY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60))
        );
        jP_ConteudoLayout.setVerticalGroup(
            jP_ConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_ConteudoLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jP_ConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jP_FundoVY, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jP_FundoVX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jL_Igual, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jP_OpcoesEResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jL_Mensagem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jB_Limpar)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jP_Fundo2Layout = new javax.swing.GroupLayout(jP_Fundo2);
        jP_Fundo2.setLayout(jP_Fundo2Layout);
        jP_Fundo2Layout.setHorizontalGroup(
            jP_Fundo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_Fundo2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_Fundo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jP_Conteudo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jP_FundoTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jP_Fundo2Layout.setVerticalGroup(
            jP_Fundo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_Fundo2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jP_FundoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jP_Conteudo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jP_FundoLayout = new javax.swing.GroupLayout(jP_Fundo);
        jP_Fundo.setLayout(jP_FundoLayout);
        jP_FundoLayout.setHorizontalGroup(
            jP_FundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_FundoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jP_Fundo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jP_FundoLayout.setVerticalGroup(
            jP_FundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_FundoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jP_Fundo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP_Fundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP_Fundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jB_AdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_AdicaoActionPerformed
        Operacoes op = new Operacoes();
        
        try {
            String respSoma = op.Soma(Double.parseDouble(jTF_ValorX.getText()),Double.parseDouble(jTF_ValorY.getText()));
            jTF_Resultado.setText(respSoma);
            jL_Mensagem.setText("");
        } catch (NumberFormatException ex) {
            jL_Mensagem.setText("É necessário inserir apenas números");
        }
    }//GEN-LAST:event_jB_AdicaoActionPerformed

    private void jB_SubtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_SubtracaoActionPerformed
        Operacoes op = new Operacoes();
        
        try {
            String respSoma = op.Subtracao(Double.parseDouble(jTF_ValorX.getText()),Double.parseDouble(jTF_ValorY.getText()));
            jTF_Resultado.setText(respSoma);
            jL_Mensagem.setText("");
        } catch (NumberFormatException ex) {
            jL_Mensagem.setText("É necessário inserir apenas números");
        }
    }//GEN-LAST:event_jB_SubtracaoActionPerformed

    private void jB_MultiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_MultiplicacaoActionPerformed
        Operacoes op = new Operacoes();
        
        try {
            String respSoma = op.Multiplicacao(Double.parseDouble(jTF_ValorX.getText()),Double.parseDouble(jTF_ValorY.getText()));
            jTF_Resultado.setText(respSoma);
            jL_Mensagem.setText("");
        } catch (NumberFormatException ex) {
            jL_Mensagem.setText("É necessário inserir apenas números");
        }
    }//GEN-LAST:event_jB_MultiplicacaoActionPerformed

    private void jB_DivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_DivisaoActionPerformed
        Operacoes op = new Operacoes();
        
        try {
            String respSoma = op.Divisao(Double.parseDouble(jTF_ValorX.getText()),Double.parseDouble(jTF_ValorY.getText()));
            jTF_Resultado.setText(respSoma);
            jL_Mensagem.setText("");
        } catch (NumberFormatException ex) {
            jL_Mensagem.setText("É necessário inserir apenas números");
        }
    }//GEN-LAST:event_jB_DivisaoActionPerformed

    private void jB_LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_LimparActionPerformed
        Limpar();
    }//GEN-LAST:event_jB_LimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_Adicao;
    private javax.swing.JButton jB_Divisao;
    private javax.swing.JButton jB_Limpar;
    private javax.swing.JButton jB_Multiplicacao;
    private javax.swing.JButton jB_Subtracao;
    private javax.swing.JLabel jL_Igual;
    private javax.swing.JLabel jL_Igual1;
    private javax.swing.JLabel jL_Mensagem;
    private javax.swing.JLabel jL_Titulo;
    private javax.swing.JPanel jP_Conteudo;
    private javax.swing.JPanel jP_Fundo;
    private javax.swing.JPanel jP_Fundo2;
    private javax.swing.JPanel jP_FundoTitulo;
    private javax.swing.JPanel jP_FundoVX;
    private javax.swing.JPanel jP_FundoVY;
    private javax.swing.JPanel jP_OpcoesEResultado;
    private javax.swing.JTextField jTF_Resultado;
    private javax.swing.JTextField jTF_ValorX;
    private javax.swing.JTextField jTF_ValorY;
    // End of variables declaration//GEN-END:variables
}
